#!/usr/bin/env node
/**
 * scripts/setup-env.mjs
 *
 * Generates all secrets needed for The Bengal Reader's push notifications
 * and writes them to .env.local (gitignored).
 *
 * Run once:  node scripts/setup-env.mjs
 * Then:      paste .env.local values into Vercel dashboard
 */

import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const OUT = resolve(process.cwd(), '.env.local');

// ── base64url ─────────────────────────────────────────────────────────────────
function b64u(buf) {
  return Buffer.from(buf).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}

// ── VAPID key pair (P-256) ────────────────────────────────────────────────────
const { privateKey, publicKey } = generateKeyPairSync('ec', { namedCurve: 'P-256' });

// SPKI DER for public key: last 65 bytes = uncompressed point (04 || x || y)
const spki = publicKey.export({ type: 'spki', format: 'der' });
const pubRaw = spki.slice(-65);

// PKCS8 DER for private key: 32 raw bytes are at offset 36
const pkcs8 = privateKey.export({ type: 'pkcs8', format: 'der' });
const privRaw = pkcs8.slice(36, 68);

const VAPID_PUBLIC_KEY  = b64u(pubRaw);
const VAPID_PRIVATE_KEY = b64u(privRaw);

// ── Random notify secret ──────────────────────────────────────────────────────
const NOTIFY_SECRET = randomBytes(32).toString('hex');

// ── Merge with existing .env.local (don't overwrite manual values) ────────────
const existing = {};
if (existsSync(OUT)) {
  readFileSync(OUT, 'utf8').split('\n').forEach(line => {
    const m = line.match(/^([^=]+)=(.*)$/);
    if (m) existing[m[1].trim()] = m[2].trim();
  });
}

const env = {
  // Manual — user must fill these in
  ANTHROPIC_API_KEY:  existing.ANTHROPIC_API_KEY  || 'sk-ant-REPLACE_ME',
  KV_REST_API_URL:    existing.KV_REST_API_URL    || 'https://REPLACE_ME.kv.vercel-storage.com',
  KV_REST_API_TOKEN:  existing.KV_REST_API_TOKEN  || 'REPLACE_ME',

  // Auto-generated — regenerated only if not already set
  VAPID_PUBLIC_KEY:   existing.VAPID_PUBLIC_KEY   || VAPID_PUBLIC_KEY,
  VAPID_PRIVATE_KEY:  existing.VAPID_PRIVATE_KEY  || VAPID_PRIVATE_KEY,
  VAPID_SUBJECT:      existing.VAPID_SUBJECT       || 'mailto:bot@bengal-reader.app',
  NOTIFY_SECRET:      existing.NOTIFY_SECRET       || NOTIFY_SECRET,
};

const content = [
  '# The Bengal Reader — environment variables',
  '# Generated by scripts/setup-env.mjs',
  '# Copy every line into Vercel: Settings → Environment Variables',
  '#',
  '# Lines marked REPLACE_ME must be filled in manually (see instructions below).',
  '',
  '# ── Claude AI (get from console.anthropic.com → API Keys) ──────────────────',
  `ANTHROPIC_API_KEY=${env.ANTHROPIC_API_KEY}`,
  '',
  '# ── Vercel KV (Vercel dashboard → Storage → Create KV → copy both values) ──',
  `KV_REST_API_URL=${env.KV_REST_API_URL}`,
  `KV_REST_API_TOKEN=${env.KV_REST_API_TOKEN}`,
  '',
  '# ── VAPID push keys (auto-generated — do not change after first deploy) ─────',
  `VAPID_PUBLIC_KEY=${env.VAPID_PUBLIC_KEY}`,
  `VAPID_PRIVATE_KEY=${env.VAPID_PRIVATE_KEY}`,
  `VAPID_SUBJECT=${env.VAPID_SUBJECT}`,
  '',
  '# ── Shared secret for GitHub Actions → /api/notify call ────────────────────',
  `NOTIFY_SECRET=${env.NOTIFY_SECRET}`,
].join('\n') + '\n';

writeFileSync(OUT, content);

console.log('\n✅  .env.local written.\n');
console.log('Next steps:\n');
console.log('  1. Open .env.local and fill in the three REPLACE_ME values:');
console.log('       ANTHROPIC_API_KEY  → https://console.anthropic.com → API Keys');
console.log('       KV_REST_API_URL  ┐');
console.log('       KV_REST_API_TOKEN ┘ → Vercel dashboard → your project → Storage → Create KV\n');
console.log('  2. Go to https://vercel.com → your project → Settings → Environment Variables');
console.log('     Paste every line from .env.local (except comments).\n');
console.log('  3. Add NOTIFY_SECRET to GitHub:');
console.log('     Repo → Settings → Secrets and variables → Actions → New secret');
console.log(`     Name: NOTIFY_SECRET   Value: ${env.NOTIFY_SECRET}\n`);
console.log('  4. Redeploy on Vercel (or just push any commit — it auto-deploys).\n');
console.log('That\'s it — push notifications and AI Q&A will be live.\n');
